"""crear accounts

Revision ID: 6580b91afb8a
Revises:
Create Date: 2026-10-10 14:02:08.803484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores de la revisión: los usa Alembic para ordenar las migraciones
revision: str = "6580b91afb8a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("balance >= 0", name=op.f("ck_accounts_balance_non_negative")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_accounts_email_lowercase")),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email", name=op.f("uq_accounts_email")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    # ### end Alembic commands ###
