"""crear transfers

Revision ID: 735f307c630f
Revises: 6580b91afb8a
Create Date: 2026-10-10 14:02:35.401604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores de la revisión: los usa Alembic para ordenar las migraciones
revision: str = "735f307c630f"
down_revision: str | Sequence[str] | None = "6580b91afb8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_user_id", sa.Uuid(), nullable=False),
        sa.Column("to_user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transfers_amount_positive")),
        sa.CheckConstraint("from_user_id <> to_user_id", name=op.f("ck_transfers_distinct_accounts")),
        sa.ForeignKeyConstraint(["from_user_id"], ["accounts.user_id"], name=op.f("fk_transfers_from_user_id_accounts")),
        sa.ForeignKeyConstraint(["to_user_id"], ["accounts.user_id"], name=op.f("fk_transfers_to_user_id_accounts")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transfers_from_user_id", "transfers", ["from_user_id", "id"], unique=False)
    op.create_index("ix_transfers_to_user_id", "transfers", ["to_user_id", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transfers_to_user_id", table_name="transfers")
    op.drop_index("ix_transfers_from_user_id", table_name="transfers")
    op.drop_table("transfers")
    # ### end Alembic commands ###
